#!/bin/bash
# 星广报表数据提取 - 快速执行指南

echo "======================================"
echo "星广报表数据提取任务"
echo "======================================"
echo ""
echo "📋 当前状态:"
echo "  - 浏览器已打开星广报表页面"
echo "  - 共38页，750条记录"
echo "  - 飞书CLI已配置"
echo ""
echo "🚀 执行步骤:"
echo ""
echo "步骤1: 在浏览器中提取数据"
echo "--------------------------------------"
echo "1. 按 F12 打开开发者工具"
echo "2. 切换到 Console (控制台) 标签"
echo "3. 复制并粘贴以下脚本:"
echo ""
echo "   文件位置: /workspace/console_extract_complete.js"
echo ""
echo "   或者直接执行:"
echo "   cat /workspace/console_extract_complete.js"
echo ""
echo "4. 脚本将自动:"
echo "   ✓ 遍历所有38页"
echo "   ✓ 提取表格数据"
echo "   ✓ 筛选消耗>2000的记录"
echo "   ✓ 自动下载CSV文件"
echo ""
echo "步骤2: 发送飞书消息"
echo "--------------------------------------"
echo "如果需要手动发送飞书消息，运行:"
echo ""
echo "  python /workspace/process_and_send.py"
echo ""
echo "======================================"
echo ""
echo "📁 生成的文件:"
echo "  - CSV文件: ~/Downloads/star_report_cost_over_2000_*.csv"
echo "  - JSON文件: /workspace/filtered_data.json (如使用Python脚本)"
echo ""
echo "📱 飞书群聊ID: oc_74cf357efbbda7b35af5078abcb29bdb"
echo ""
echo "======================================"