#!/bin/bash
# 星广报表数据提取 - 一键脚本

echo "================================================================"
echo "星广报表数据提取 - 完整流程"
echo "================================================================"
echo ""
echo "此脚本将："
echo "1. 显示自动化提取脚本的路径"
echo "2. 提供详细的使用说明"
echo "3. 提供数据整理工具"
echo ""
echo "================================================================"
echo ""

# 显示主脚本路径
echo "📍 主脚本位置："
echo "   /workspace/extract_star_report_automation.js"
echo ""

# 显示使用说明
echo "📖 使用步骤："
echo ""
echo "【第1步】在浏览器中打开星广报表页面"
echo "   https://apex.whaleidea.cn/star/report"
echo ""
echo "【第2步】确保已登录并点击查询按钮，等待数据加载"
echo ""
echo "【第3步】按 F12 打开浏览器开发者工具"
echo ""
echo "【第4步】切换到 Console（控制台）标签"
echo ""
echo "【第5步】复制并粘贴以下内容："
echo ""
cat /workspace/extract_star_report_automation.js
echo ""
echo "【第6步】按回车执行，等待自动完成"
echo "   预计耗时：约2分钟（52页 × 2秒/页）"
echo ""
echo "【第7步】数据将自动下载为JSON文件"
echo ""
echo "================================================================"
echo ""

# 提供快速查看脚本的命令
echo "💡 快速查看脚本："
echo "   cat /workspace/extract_star_report_automation.js"
echo ""
echo "💡 详细使用说明："
echo "   cat /workspace/README_使用说明.md"
echo ""
echo "💡 数据整理工具："
echo "   python3 /workspace/organize_data.py"
echo ""
echo "================================================================"
echo ""
echo "✅ 准备就绪！请按照上述步骤操作。"
echo ""
echo "提取完成后，数据将保存在："
echo "   - 浏览器下载目录: star_report_[时间戳].json"
echo "   - 浏览器全局变量: window.starReportAllData"
echo ""
echo "如需将数据移动到 /workspace/all_data.json，请运行："
echo "   python3 /workspace/organize_data.py"
echo ""
echo "================================================================"